language = "Ruby"
version = "3.1.2"
compiled = false
extension = "rb"
environment = []
build_command = []
run_command = [ "ruby", "{file}" ]
test_file = "test.rb"
aliases = ["ruby", "rb"]
should_limit_memory = true
memory_limit = 256
process_limit = 256
