language = "Go"
version = "1.18.3"
compiled = true
extension = "go"
build_command = [ "go", "build", "-o", "code", "{file}"]
run_command = [ "./code" ]
test_file = "test.go"
environment = []
aliases = [ "go", "golang" ]
